### ISSUE TITLE
Problem using on python 2.x

### ISSUE THREAD

**Issue by kubark42** [peteut/ipython-file-upload#2]
https://github.com/peteut/ipython-file-upload/blob/master/fileupload/widget.py#L33

The implementation of `super()` is not compatible with Python 2.x. The following _is_, however:

`super(FileUploadWidget, self).__init__(*args, **kwargs)`

Replacing the one with the other, everything works perfectly. Not sure if you want to extend support to both Python 2 and Python 3 (and have potentially twice as many bugs to find. : ).

In any case, thanks a million for this library, it's exactly what we needed!

**Comment by peteut** [comment]
@kubark42 nice to hear it works for you.

**Comment by den-run-ai** [comment]
@kubark42 I'm hitting tons of bugs - how did you get this working, can you show your pip list and any additional installation instructions for nbextension, javascript, etc.?
