### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by oschuett** [peteut/ipython-file-upload#21]
Hi Alain,

I was wondering if you could make a new release and upgrade the PyPI package accordingly?

Cheers,
Ole

**Comment by peteut** [comment]
@oschuett : I'll try to do it tonight. 

Regards,
Alain

**Comment by peteut** [comment]
@oschuett: Created a PyPI package: [0.1.3](https://pypi.python.org/pypi/fileupload/)..

Regards,
Alain

**Comment by oschuett** [comment]
Thanks for the quick response :-)

... however, it seems something went wrong. Apparently, you made a second release of edea1d1 after removing the last three commits:

dd50b5d Merge pull request #16 from oschuett/master
dae89e7 Make button label a traitlet
4593e48 fix typo
edea1d1 add missing `install` instruction

The commits are still in the repro, probably because my PR references them. So, it should be straightforward to fix.

Cheers,
Ole

**Comment by peteut** [comment]
Very sorry for that. 

Best,
Alain

**Comment by oschuett** [comment]
Hi Alain,

thanks a lot for the new package :-)

Just one last remark: For ipywidgets it is common to install the static files directly into share/jupyter/nbextensions/. This saves one from having to call "jupyter nbextension install". 

See e.g.: https://github.com/arose/nglview/blob/master/setup.py#L173

Cheers,
Ole

**Comment by peteut** [comment]
Thanks for the hint, I'll look into that. See also #22.
