### ISSUE TITLE
No PermissionError for Python 2.7

### ISSUE THREAD

**Issue by fbnrst** [peteut/ipython-file-upload#3]
I just tried to install ipython-file-upload and got the error `NameError: global name 'PermissionError' is not defined`. I found that there
[> was no PermissionError in Python 2.7, it was introduced in the Python 3.3](http://stackoverflow.com/a/18199529/5142797).
I'd suggest to add Python 3 a requirement or adopt the code for python 2.7 compatibility.

**Comment by peteut** [comment]
Thanks for the hint, I'll fix it soon.

**Comment by peteut** [comment]
_Explicit is better than implicit._, I'm also going to factor out the install task to a function, like in [qgrid.nbinstall](https://github.com/quantopian/qgrid/blob/master/qgrid/__init__.py#L9).

**Comment by den-run-ai** [comment]
@peteut looks like your fix was not verified by @fabianrost84, not sure why you closed the issue?

**Comment by fbnrst** [comment]
Currently, I do not have the time to verify the fix but I'm alright with closing it.
