### ISSUE TITLE
compatible with ipywidgets 5+?

### ISSUE THREAD

**Issue by den-run-ai** [peteut/ipython-file-upload#9]
pip list:

alabaster (0.7.7)
anaconda-client (1.4.0)
anaconda-navigator (1.1.0)
argcomplete (1.0.0)
astropy (1.1.2)
Babel (2.2.0)
backports-abc (0.4)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.4.1)
bitarray (0.8.1)
blaze (0.9.1)
bokeh (0.11.1)
boto (2.39.0)
Bottleneck (1.0.0)
cdecimal (2.3)
cffi (1.5.2)
chest (0.2.3)
cloudpickle (0.1.1)
clyent (1.2.1)
colorama (0.3.7)
comtypes (1.1.2)
conda (4.0.5)
conda-build (1.20.0)
conda-env (2.4.5)
conda-manager (0.3.1)
configobj (5.0.6)
configparser (3.3.0.post2)
cryptography (1.3)
cycler (0.10.0)
Cython (0.23.4)
cytoolz (0.7.5)
dask (0.8.1)
datashape (0.5.1)
decorator (4.0.9)
dill (0.2.4)
docopt (0.6.2)
docutils (0.12)
entrypoints (0.2.1)
enum34 (1.1.2)
et-xmlfile (1.0.1)
fastcache (1.0.2)
fileupload (0.1.1)
Flask (0.10.1)
Flask-Cors (2.1.2)
funcsigs (0.4)
futures (3.0.3)
gevent (1.1.0)
greenlet (0.4.9)
grin (1.2.1)
h5py (2.5.0)
haxor (0.3.1)
HeapDict (1.0.0)
idna (2.0)
ipaddress (1.0.14)
ipykernel (4.3.1)
ipython (4.2.0)
ipython-genutils (0.1.0)
ipywidgets (5.1.3)
itsdangerous (0.24)
jdcal (1.2)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.4.0)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
jupyter-kernel-gateway (0.5.1)
llvmlite (0.9.0)
locket (0.2.0)
lxml (3.6.0)
MarkupSafe (0.23)
matplotlib (1.5.1)
menuinst (1.3.2)
mistune (0.7.2)
mpmath (0.19)
multipledispatch (0.4.8)
nbconvert (4.2.0)
nbformat (4.0.1)
networkx (1.11)
nltk (3.2)
nose (1.3.7)
notebook (4.2.0)
numba (0.24.0)
numexpr (2.5)
numpy (1.10.4)
odo (0.4.2)
openpyxl (2.3.2)
pandas (0.18.0)
partd (0.3.2)
path.py (0.0.0)
pathlib2 (2.1.0)
patsy (0.4.0)
pep8 (1.7.0)
pickleshare (0.7.2)
Pillow (3.1.1)
pip (8.1.1)
ply (3.8)
prompt-toolkit (0.60)
psutil (3.4.2)
ptipython (1.0.0)
ptpython (0.32)
py (1.4.31)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pyflakes (1.1.0)
Pygments (2.1.3)
PyInstaller (3.1.1)
pyodbc (3.0.10)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyreadline (2.1)
pytest (2.8.5)
Python-contrib-nbextensions (alpha)
python-dateutil (2.5.1)
pythonnet (2.1.0)
pytz (2016.2)
pywin32 (220)
PyYAML (3.11)
pyzmq (15.2.0)
QtAwesome (0.3.2)
qtconsole (4.2.0)
QtPy (1.0)
requests (2.10.0)
rope (0.9.4)
scandir (1.2)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scipy (0.17.0)
seaborn (0.7.0)
setuptools (21.0.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
snowballstemmer (1.2.1)
sockjs-tornado (1.0.1)
sphinx (1.3.5)
sphinx-rtd-theme (0.1.9)
spyder (2.3.8)
SQLAlchemy (1.0.12)
statsmodels (0.6.1)
sympy (1.0)
tables (3.2.2)
toolz (0.7.4)
tornado (4.3)
traitlets (4.2.1)
unicodecsv (0.14.1)
wcwidth (0.1.6)
Werkzeug (0.11.4)
wheel (0.29.0)
widgetsnbextension (1.2.2)
xlrd (0.9.4)
XlsxWriter (0.8.4)
xlwings (0.7.0)
xlwt (1.0.0)

**Comment by peteut** [comment]
Updated `master` to use `ipywidgets>=5.1`.
